### ISSUE TITLE
Human readable error message when starting node, error 504

### ISSUE THREAD

**Issue by dimsome** [usecannon/cannon#117] opened 2023-02-07 07:19 UTC
Recently it happens that the command: `cannon synthetix-sandbox` produces a long error message that is longer than the entire console history, see screenshot.

![Screen Shot 2023-02-07 at 14 16 28](https://user-images.githubusercontent.com/69167058/217174170-2d77ead5-2617-42a2-adf2-b3640f9059fd.png)

It seems to log the entire request/response http object.

Scrolling a bit further the response starts with:

```
status: 504,
statusText: 'Gateway Timeout',
```

It would be nice if there was a method to check if the response object contains an error and log an appropriate message that is helpful for a user.

**Comment by dbeal-eth** [comment] 2023-03-26 22:42
thanks for the suggestion, will be fixed in the next release :+1:

**Comment by dbeal-eth** [comment] 2023-04-07 19:56
fixed by https://github.com/usecannon/cannon/pull/151

also quick note @dimsome , the error you are seeing is likely caused by Infura IPFS service not being a "real" IPFS service. we have noticed Infura IPFS has extreme trouble resolving artifacts from outside its own, and vise versa. We also reached out to their support and they confirmed as much. Therefore, we reccomend not using Infura IPFS at all for the time being.

**Closed by dbeal-eth** 2023-04-07 19:56 UTC
